### ISSUE TITLE
Task does not fail, if cmd failed

### ISSUE THREAD

**Issue by stuikomma** [tandrewnichols/simple-cli#10]
Hi, we are facing an issue running [grunt-simple-nyc](https://github.com/tandrewnichols/grunt-simple-nyc), since the tests don't fail anymore. I tracked the issue to https://github.com/tandrewnichols/simple-cli/blob/master/lib/builder.js#L229, where grunt's `done` function is called with the exit code of the child process.

This should rather be `this.callback(code === 0);` according to the [grunt docs](https://gruntjs.com/api/inside-tasks#this.async).

> Either false or an Error object may be passed to the done function to instruct Grunt that the task has failed.

IMO this has to work as expected without supplying a custom callback. I guess the README would have to be updated [here](https://github.com/tandrewnichols/simple-cli#callback) and [here](https://github.com/tandrewnichols/simple-cli#oncomplete).

**Comment by tandrewnichols** [comment]
Thanks for reporting the issue! I believe you're right about that. I'll have a look when I get some time. I'm actually in the hospital for the birth of my child at the moment, so I probably won't get to immediately. Pull request welcome as well.

**Comment by stuikomma** [comment]
Alright, no hurry then! Enjoy these precious moments and we'll revert to using grunt-shell for the meantime.

If I find time first, I'll make a PR.

All the best! 😃

**Comment by tandrewnichols** [comment]
Fixed in v5.0.2
