### ISSUE TITLE
win-spawn is deprecated

### ISSUE THREAD

**Issue by stuikomma** [tandrewnichols/simple-cli#11]
[win-spawn](https://www.npmjs.com/package/win-spawn) says
> use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.

Just dropping in `cross-spawn` [everywhere](https://github.com/tandrewnichols/simple-cli/search?q=win-spawn&unscoped_q=win-spawn) should do the job.

**Comment by tandrewnichols** [comment]
Ok, cool. Thanks. I will try to pick that up when I get some time (as I mentioned in the other issue, we just had a baby, so it won't be immediately, but PR is welcome if it's urgent).

**Comment by tandrewnichols** [comment]
Fixed in v5.0.2
