### ISSUE TITLE
"Warning: Cannot find module 'npm' Used --force, continuing."

### ISSUE THREAD

**Issue by raijinsetsu** [tandrewnichols/simple-cli#12]
I started with the grunt-simple-npm module but none of the options were working correctly. I've moved on to using this module directly in my grunt script.

However, it appears that the module only works with CLIs that have been installed by NPM which does not match up with the documentation.

builder.js line 27 seems to be where the exception is being thrown because it is indirectly calling "require.resolve" on the command and it's not found.

Is this a bug or just a problem with the documentation?

**Comment by raijinsetsu** [comment]
Found this commit to be the one that looks like it broke this functionality:
https://github.com/tandrewnichols/simple-cli/commit/32be8c6c9e44907d660f933534c9d7bee44d54b5

**Comment by tandrewnichols** [comment]
I think it's possible that `grunt-simple-npm` just needs to updated. It's using v2.0.0 of this library, but the most recent is v5.0.2, so if you're looking at the default README for this repo (i.e. not selecting the v2.0.0 tag), things probably are going to work differently.

**Comment by raijinsetsu** [comment]
Sorry. I wasn't clear.

I found that grunt-simple-npm was too far behind. I looked at the module and saw that it simply a wrapper around this module, simple-cli. I removed grunt-simple-npm and I am now using simple-cli directly.

However, v5 broke the ability to invoke anything that is not an NPM module by calling "require.resolve" which throws an exception when the module does not resolve. Downgrading to v4 allows me to invoke ANY command line, not just those in my node_modules folder.

**Comment by tandrewnichols** [comment]
Oh, you mean it doesn't work for global binaries? That surprises me I guess cause the `require.resolve` is only adding `node_modules/.bin` to `PATH` for the command, so it _should_ still keep your existing PATH, and therefore find the global binary. But I've never used it this way and it's hard to test that kind of scenario, so yeah, it's totally possible that it's wrong.

**Comment by raijinsetsu** [comment]
The call to require.resolve is throwing an exception as far as I can tell.

**Comment by tandrewnichols** [comment]
That's weird. What version of node are you on?

**Comment by tandrewnichols** [comment]
Nope, nm. That actually does fail for me in my testing as well. I wonder if that changed, or if I'm just a doofus and it's always been that way.

**Comment by tandrewnichols** [comment]
Oh . . . wait. That commit you linked isn't using `require.resolve`. It's using `path.resolve`. And I'm also confused because that commit is not the most recent version of this module.

Anyway . . . I think the problem is that if you _don't_ have a local version of the binary, then `require.resolve` does throw an error. So probably try/catch is good enough to fix it.

**Comment by tandrewnichols** [comment]
Published a fix as 5.0.3

**Comment by tandrewnichols** [comment]
I'm updating grunt-simple-npm to use the latest version of simple-cli as well.

**Comment by tandrewnichols** [comment]
`grunt-simple-npm@^2` now uses `simple-cli@^5`
